# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'Visit Sandpoint Idaho' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  ## Pods for Visit Sandpoint Idaho

  # Firebase
  pod 'Firebase/Firestore'    # Cloud Firestore
  pod 'Firebase/Analytics'    # Google Analytics
  pod 'Firebase/Crashlytics'  # Firebase Crashlytics
  pod 'Firebase/Auth'         # Authentication
  pod 'Firebase/Storage'      # Cloud Storage

  pod 'SDWebImage', '~> 5.0'  # Image downloading and caching

end
