# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'Visit Sandpoint Idaho' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  ## Pods for Visit Sandpoint Idaho

  # Firebase
  pod 'Firebase/Firestore', '7.4.0'    # Cloud Firestore
  # pod 'Firebase/Analytics', '7.4.0'    # Google Analytics (not working with M1 yet)
  pod 'Firebase/Crashlytics', '7.4.0'  # Firebase Crashlytics
  pod 'Firebase/Auth', '7.4.0'         # Authentication
  pod 'Firebase/Storage', '7.4.0'      # Cloud Storage

  pod 'SDWebImage', '~> 5.0'  # Image downloading and caching

end
